version: "3"
services: 
  app:
    container_name: server_container
    restart: always
    build: .
    ports:
      - 5000:5000
    links:
      - mongo
    env_file:
      - .env
  mongo:
    container_name: "mongo_db_container"
    image: mongo:4.2.16-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env
    volumes: 
      - ./db-data/mongo/:/data/db